{
  "hash": "3c9859863ce4efb385b79f588f69bf35",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Verify the Claim: Philadelphia Poverty Change\"\nsubtitle: \"Testing if ACS data supports the 2018 news story\"\nauthor: Gautami Kasat\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-summary: \"View Code\"\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## The Enquiry\n\nThis report tests whether the ACS data supports the claims in Alfred Lubrano's 2018 article, [\"New Census figures on Philly neighborhoods show inequality, high numbers of whites living in poverty\"](https://whyy.org/articles/new-census-figures-on-philly-neighborhoods-show-inequality-high-numbers-of-whites-living-in-poverty/) (WHYY / Philadelphia Inquirer, December 6, 2018). \n\n\n\n\n## Part 1: Reconstruct\n\n### Variables\nI pulled four ACS variables. For overall poverty, B17001_002 counts people below the poverty level in the past twelve months, and B17001_001 gives the population for whom poverty status is determined. Because several claims are specifically about white poverty, I also pulled B17001A_001 and B17001A_002, the same table restricted to people identifying as white alone. ACS publishes counts, not rates, so both the rate and its margin of error have to be calculated. I used the 2006-2010 and 2013-2017 five-year estimates at the census tract level. Five-year estimates are the only ones that reach tracts; one-year estimates cover only areas of 65,000 people or more.\n\n### Assumptions\nThe article does not document its method, so several choices are mine. It does not name the ACS table it used; I assumed B17001. It says \"white\" without defining it, so I used B17001A, white alone, which includes people who also identify as Hispanic. And it reports neighborhood figures, which are not Census geographies: its reporters aggregated tracts into boundaries of their own choosing and never published which tracts went where, so my numbers will not match theirs. Every figure in the article is a point estimate, with no margins of error given. \n\n### Overlap\nThe two periods do not overlap. Census Bureau guidance is explicit that only non-overlapping five-year estimates should be compared over time, so on this point the article is on solid ground.\n\n\n## Part 2: Test (code plus interpretation)\n\n### Computing poverty rates\nACS publishes counts, not rates, so both the rate and its uncertainty have to be built. Dividing the count below poverty by the universe gives the rate; `moe_prop()` then combines the two margins of error into a margin of error for the resulting proportion. The count's margin of error does not carry over.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_2010 <- pov_2010 %>%\n  mutate(\n    pov_pct = pov_poorE / pov_totalE * 100,\n    pov_moe = moe_prop(pov_poorE, pov_totalE, pov_poorM, pov_totalM) * 100,\n    wht_pct = wht_poorE / wht_totalE * 100,\n    wht_moe = moe_prop(wht_poorE, wht_totalE, wht_poorM, wht_totalM) * 100\n    )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_2017 <- pov_2017 %>%\n  mutate(\n    pov_pct = pov_poorE / pov_totalE * 100,\n    pov_moe = moe_prop(pov_poorE, pov_totalE, pov_poorM, pov_totalM) * 100,\n    wht_pct = wht_poorE / wht_totalE * 100,\n    wht_moe = moe_prop(wht_poorE, wht_totalE, wht_poorM, wht_totalM) * 100\n    )\n```\n:::\n\n\n### Assessing reliability\n\nThe coefficient of variation (CV) expresses the uncertainty as a share of the estimate, which makes estimates comparable. Following Jurjevich et al. (2018), I flagged a CV under 12% as reliable, 12 to 40% as somewhat reliable, and above 40% as unreliable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_2010 <- pov_2010 %>%\n  mutate(\n    pov_cv = (pov_moe/1.645) / pov_pct * 100,\n    pov_reliability = case_when(\n    pov_cv < 12 ~ \"Reliable\",\n    pov_cv < 40 ~ \"Somewhat reliable\",\n    pov_cv >= 40 ~ \"Unreliable\",\n    TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_2010 <- pov_2010 %>%\n  mutate(\n    wht_cv = (wht_moe/1.645) / wht_pct * 100,\n    wht_reliability = case_when(\n    wht_cv < 12 ~ \"Reliable\",\n    wht_cv < 40 ~ \"Somewhat reliable\",\n    wht_cv >= 40 ~ \"Unreliable\",\n    TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_2017 <- pov_2017 %>%\n  mutate(\n    pov_cv = (pov_moe/1.645) / pov_pct * 100,\n    pov_reliability = case_when(\n    pov_cv < 12 ~ \"Reliable\",\n    pov_cv < 40 ~ \"Somewhat reliable\",\n    pov_cv >= 40 ~ \"Unreliable\",\n    TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_2017 <- pov_2017 %>%\n  mutate(\n    wht_cv = (wht_moe/1.645) / wht_pct * 100,\n    wht_reliability = case_when(\n    wht_cv < 12 ~ \"Reliable\",\n    wht_cv < 40 ~ \"Somewhat reliable\",\n    wht_cv >= 40 ~ \"Unreliable\",\n    TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n### Observations\nReliability differs sharply between the two measures, and between the two periods. For overall poverty, 45 of 384 tracts were unreliable in 2006-2010, falling to 22 by 2013-2017. For white poverty the picture is far worse: 189 tracts, just under half the city, were unreliable in 2006-2010, improving to 111 by 2013-2017. This asymmetry matters because the article's white poverty claims are claims about change, and a change is only as sound as its weaker endpoint. In roughly half of Philadelphia, that endpoint will not hold.\n\n### Measuring change \n\nTo compare the two periods, each tract's 2010 and 2017 rates have to sit in the same row, so I joined the two datasets on GEOID. The change itself is simple subtraction, but its uncertainty is not: a difference between two estimates is less certain than either estimate alone, and the two margins of error combine by squaring, adding, and taking the square root rather than by simple addition. Dividing the change by that combined standard error gives a z score, which says how large the movement is relative to the noise around it. At 90% confidence the threshold is 1.645: above it, the change is distinguishable from zero; below it, the data cannot establish that anything happened.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_change <- pov_2010 %>%\n  st_drop_geometry() %>%\n  select(GEOID, NAME, pov_pct, pov_moe, wht_pct, wht_moe) %>%\n  rename(pov_pct_10 = pov_pct, pov_moe_10 = pov_moe,\n         wht_pct_10 = wht_pct, wht_moe_10 = wht_moe) %>%\n  left_join(\n    pov_2017 %>%\n      select(GEOID, pov_pct, pov_moe, wht_pct, wht_moe) %>%\n      rename(pov_pct_17 = pov_pct, pov_moe_17 = pov_moe,\n             wht_pct_17 = wht_pct, wht_moe_17 = wht_moe),\n    by = \"GEOID\"\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_change <- pov_change %>%\n  mutate(\n    pov_change = pov_pct_17 - pov_pct_10,\n    pov_se_diff = sqrt((pov_moe_10/ 1.645)^2 + (pov_moe_17/ 1.645)^2),\n    pov_moe_diff = pov_se_diff * 1.645,\n    pov_z = pov_change / pov_se_diff,\n    pov_sig = abs(pov_z) > 1.645\n    )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_change <- pov_change %>%\n  mutate(\n    wht_change = wht_pct_17 - wht_pct_10,\n    wht_se_diff = sqrt((wht_moe_10/ 1.645)^2 + (wht_moe_17/ 1.645)^2),\n    wht_moe_diff = wht_se_diff * 1.645,\n    wht_z = wht_change / wht_se_diff,\n    wht_sig = abs(wht_z) > 1.645\n    )\n```\n:::\n\n\n### Missing values\n\n\nEight tracts produce no poverty rate in one or both periods. Seven of them carry numbers in the 9803 to 9809 range, which the Census Bureau reserves for special land use tracts: large areas with little or no residential population, such as parks, airports, and industrial or employment zones. \n\nThe eighth, Tract 50, sits at the southern tip of the city along the Delaware and behaves the same way. In all eight, the population for whom poverty status can be determined is effectively zero, so there is no rate to compute and the `NA` is correct rather than a gap in the data. I excluded them from the tract counts that follow. \n\nSix further tracts drop out of the white poverty analysis for a different reason. Each has a measurable white poverty rate in one period but not the other, because the white population for whom poverty status could be determined was zero in the other period. Tract 103 is the clearest case: a white poverty rate of 100% in 2006-2010 and no measurable white population at all by 2013-2017. With no second endpoint there is no change to test, so these tracts are excluded from the white analysis but retained in the overall one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(pov_change, pov_sig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  pov_sig     n\n  <lgl>   <int>\n1 FALSE     313\n2 TRUE       63\n```\n\n\n:::\n:::\n\n\n### How many tracts changed\n\nOf the 376 tracts with a measurable poverty rate in both periods, 63 show a change that is statistically distinguishable from zero at 90% confidence. The remaining 313, just over 83%, do not. That does not mean poverty held steady in those tracts; it means the data cannot establish that it moved. For most of Philadelphia, the margin of error on a seven-year change is wider than the change itself.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_change  %>%\n  arrange(pov_change) %>%\n  mutate(rank = row_number()) %>%\n  ggplot(aes(x = rank, y = pov_change)) +\n  geom_errorbar(aes(ymin = pov_change - pov_moe_diff,\n                    ymax = pov_change + pov_moe_diff,\n                    color = pov_sig),\n                    width = 0, alpha = 0.4)+\n  geom_point(aes(color = pov_sig), size = 0.5)+\n  scale_color_manual(\n    values = c(\"TRUE\" = \"#1f5c8b\", \"FALSE\" = \"grey75\"),\n    labels = c(\"TRUE\" = \"Detectable\", \"FALSE\" = \"Not detectable\"),\n    name = NULL\n  ) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", linewidth = 0.3) +\n  scale_x_continuous(breaks = seq(0, 376, by = 50)) +\n  coord_cartesian(ylim = c(-60, 60)) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 12, face = \"bold\"),\n    plot.subtitle = element_text(size = 10, color = \"grey30\"),\n    plot.caption = element_text(size = 7, color = \"grey50\", hjust = 0),\n    axis.title = element_text(size = 9, color = \"grey30\"),\n    axis.text = element_text(size = 8),\n    legend.text = element_text(size = 8),\n    legend.position = \"bottom\",\n    panel.grid = element_blank()\n  ) +\n  labs(\n    title = \"Most Philadelphia tracts show no detectable change in poverty\",\n    subtitle = \"Poverty rate change between the 2006-2010 and 2013-2017 ACS estimates\",\n    caption = str_wrap(\"Axis limited to ±60 points for readability; a small number of tracts have margins of error exceeding the possible range of the scale.\", 100),\n     x = \"Each tract, ordered from largest decline to largest increase\", \n    y = \"Change in poverty rate (% points)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Kasat_Assignment_3_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThe article's most striking white poverty figures are its lowest ones: 2% in Holmesburg, 1% in Mayfair. The table below shows the fifteen Philadelphia tracts with the lowest white poverty rates in 2006-2010, the period those claims start from. Every one of them carries a coefficient of variation above the reliability threshold, several by an order of magnitude. A rate of 1% or 2% in a tract with few white residents is not a precise measurement of a small number; it is an imprecise measurement that happens to land on a small number.\n\n## Where the article's smallest numbers come from\nThe article's most striking white poverty figures are its smallest: 2% in Holmesburg, 1% in Mayfair. The first table below shows the fifteen tracts with the lowest white poverty rates in 2006-2010, the period those claims start from. Thirteen of the fifteen are unreliable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_2010 %>%\n   filter(!is.na(wht_pct), wht_pct > 0, wht_pct < 10) %>%\n  arrange(wht_pct) %>%\n  slice_head(n = 15) %>%\n  mutate(\n    dot = case_when(\n      wht_cv < 12 ~ \"🟢\",\n      wht_cv <= 40 ~ \"🟡\",\n      TRUE ~ \"🔴\"\n    ),\n    NAME = str_remove(NAME, \", Philadelphia County, Pennsylvania\")\n  ) %>%\n  select(dot, NAME, wht_pct, wht_moe, wht_cv, wht_reliability) %>%\n  gt() %>%\n  fmt_number(columns = c(wht_pct, wht_moe, wht_cv), decimals = 1) %>%\n  cols_label(\n    dot = \"\",\n    NAME = \"Tract\",\n    wht_pct = \"Rate (%)\",\n    wht_moe = \"MOE\",\n    wht_cv = \"CV (%)\",\n    wht_reliability = \"Reliability\"\n  ) %>%\n  cols_align(align = \"center\", columns = dot) %>%\n  tab_header(\n    title = \"The lowest white poverty rates are the least reliable\",\n    subtitle = \"Fifteen tracts with the lowest white poverty rates, 2006-2010 ACS\"\n  ) %>%\n  tab_source_note(\n    \"Reliability thresholds follow Jurjevich et al. (2018): CV < 12% reliable, 12-40% somewhat reliable, > 40% unreliable.\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yeodvkzqop\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yeodvkzqop table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yeodvkzqop thead, #yeodvkzqop tbody, #yeodvkzqop tfoot, #yeodvkzqop tr, #yeodvkzqop td, #yeodvkzqop th {\n  border-style: none;\n}\n\n#yeodvkzqop p {\n  margin: 0;\n  padding: 0;\n}\n\n#yeodvkzqop .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yeodvkzqop .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yeodvkzqop .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yeodvkzqop .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yeodvkzqop .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yeodvkzqop .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yeodvkzqop .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yeodvkzqop .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yeodvkzqop .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yeodvkzqop .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yeodvkzqop .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yeodvkzqop .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yeodvkzqop .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yeodvkzqop .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yeodvkzqop .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yeodvkzqop .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yeodvkzqop .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yeodvkzqop .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yeodvkzqop .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yeodvkzqop .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yeodvkzqop .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yeodvkzqop .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yeodvkzqop .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yeodvkzqop .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yeodvkzqop .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yeodvkzqop .gt_left {\n  text-align: left;\n}\n\n#yeodvkzqop .gt_center {\n  text-align: center;\n}\n\n#yeodvkzqop .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yeodvkzqop .gt_font_normal {\n  font-weight: normal;\n}\n\n#yeodvkzqop .gt_font_bold {\n  font-weight: bold;\n}\n\n#yeodvkzqop .gt_font_italic {\n  font-style: italic;\n}\n\n#yeodvkzqop .gt_super {\n  font-size: 65%;\n}\n\n#yeodvkzqop .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yeodvkzqop .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yeodvkzqop .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yeodvkzqop .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yeodvkzqop .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yeodvkzqop .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yeodvkzqop .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yeodvkzqop .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yeodvkzqop div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>The lowest white poverty rates are the least reliable</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Fifteen tracts with the lowest white poverty rates, 2006-2010 ACS</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dot\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"NAME\">Tract</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wht_pct\">Rate (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wht_moe\">MOE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wht_cv\">CV (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wht_reliability\">Reliability</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 236</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">0.9</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">1.4</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">97.7</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 384</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">1.2</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">1.1</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">53.9</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 220</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">1.6</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">2.6</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">95.9</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 267</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">2.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">90.0</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 305.02</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">2.3</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">2.1</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">57.3</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 351</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">2.3</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">1.4</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">36.0</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 10.01</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">2.3</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">2.7</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">70.3</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 339</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">75.7</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 365.02</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">2.0</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">51.3</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 352</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">2.7</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">1.6</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">37.2</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 136.01</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">2.8</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">51.2</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 308</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">1.9</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">40.2</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 255</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">3.4</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">3.8</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">66.4</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 61</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">4.5</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">78.5</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 270</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">3.7</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">65.0</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"6\">Reliability thresholds follow Jurjevich et al. (2018): CV &lt; 12% reliable, 12-40% somewhat reliable, &gt; 40% unreliable.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n#### The same problem at the other end of the scale\n\nThe second table shows the opposite end of the range, and the picture barely improves. Only two of the fifteen highest rates are reliable, and eight report a rate of exactly 100% with margins of error between 117 and 236 percentage points, on a scale that can only run from 0 to 100. The problem is not the size of the rate. It is the size of the population underneath it: a tract with a dozen white residents produces an unusable estimate whether the rate comes out at 2% or 100%. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_2010 %>%\n   filter(!is.na(wht_pct), wht_pct > 0) %>%\n  arrange(desc(wht_pct)) %>%\n  slice_head(n = 15) %>%\n  mutate(\n    dot = case_when(\n      wht_cv < 12 ~ \"🟢\",\n      wht_cv <= 40 ~ \"🟡\",\n      TRUE ~ \"🔴\"\n    ),\n    NAME = str_remove(NAME, \", Philadelphia County, Pennsylvania\")\n  ) %>%\n  select(dot, NAME, wht_pct, wht_moe, wht_cv, wht_reliability) %>%\n  gt() %>%\n  fmt_number(columns = c(wht_pct, wht_moe, wht_cv), decimals = 1) %>%\n  cols_label(\n    dot = \"\",\n    NAME = \"Tract\",\n    wht_pct = \"Rate (%)\",\n    wht_moe = \"MOE\",\n    wht_cv = \"CV (%)\",\n    wht_reliability = \"Reliability\"\n  ) %>%\n  cols_align(align = \"center\", columns = dot) %>%\n  tab_header(\n    title = \"Even the highest white poverty rates are mostly unreliable\",\n    subtitle = \"Fifteen tracts with the highest white poverty rates, 2006-2010 ACS\"\n  ) %>%\n  tab_source_note(\n    \"Reliability thresholds follow Jurjevich et al. (2018): CV < 12% reliable, 12-40% somewhat reliable, > 40% unreliable.\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ngtawmvejp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ngtawmvejp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ngtawmvejp thead, #ngtawmvejp tbody, #ngtawmvejp tfoot, #ngtawmvejp tr, #ngtawmvejp td, #ngtawmvejp th {\n  border-style: none;\n}\n\n#ngtawmvejp p {\n  margin: 0;\n  padding: 0;\n}\n\n#ngtawmvejp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ngtawmvejp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ngtawmvejp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ngtawmvejp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ngtawmvejp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ngtawmvejp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ngtawmvejp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ngtawmvejp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ngtawmvejp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ngtawmvejp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ngtawmvejp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ngtawmvejp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ngtawmvejp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ngtawmvejp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ngtawmvejp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngtawmvejp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ngtawmvejp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ngtawmvejp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ngtawmvejp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngtawmvejp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ngtawmvejp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngtawmvejp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ngtawmvejp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngtawmvejp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ngtawmvejp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngtawmvejp .gt_left {\n  text-align: left;\n}\n\n#ngtawmvejp .gt_center {\n  text-align: center;\n}\n\n#ngtawmvejp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ngtawmvejp .gt_font_normal {\n  font-weight: normal;\n}\n\n#ngtawmvejp .gt_font_bold {\n  font-weight: bold;\n}\n\n#ngtawmvejp .gt_font_italic {\n  font-style: italic;\n}\n\n#ngtawmvejp .gt_super {\n  font-size: 65%;\n}\n\n#ngtawmvejp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ngtawmvejp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ngtawmvejp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ngtawmvejp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ngtawmvejp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ngtawmvejp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ngtawmvejp .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ngtawmvejp .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ngtawmvejp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>Even the highest white poverty rates are mostly unreliable</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Fifteen tracts with the highest white poverty rates, 2006-2010 ACS</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dot\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"NAME\">Tract</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wht_pct\">Rate (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wht_moe\">MOE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wht_cv\">CV (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wht_reliability\">Reliability</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 83.01</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">100.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">214.2</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">130.2</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 103</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">100.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">217.6</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">132.3</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 106</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">100.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">235.7</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">143.3</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 151.02</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">100.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">178.1</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">108.3</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 152</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">100.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">117.3</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">71.3</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 167.02</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">100.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">189.6</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">115.3</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 174</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">100.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">218.6</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">132.9</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 31</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">100.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">181.2</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">110.1</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 88.01</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">95.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">17.3</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">11.1</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 279.02</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">92.3</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">119.7</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">78.9</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 203</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">88.6</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">18.6</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">12.8</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 364</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">87.2</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">19.8</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">13.8</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 147</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">85.8</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">5.9</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">4.2</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 145</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">85.4</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">85.9</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">61.1</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 88.02</td>\n<td headers=\"wht_pct\" class=\"gt_row gt_right\">85.0</td>\n<td headers=\"wht_moe\" class=\"gt_row gt_right\">18.1</td>\n<td headers=\"wht_cv\" class=\"gt_row gt_right\">13.0</td>\n<td headers=\"wht_reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"6\">Reliability thresholds follow Jurjevich et al. (2018): CV &lt; 12% reliable, 12-40% somewhat reliable, &gt; 40% unreliable.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nAcross the city the pattern holds. Of Philadelphia's 384 tracts in 2006-2010, just 6 produce a white poverty rate that meets the standard threshold for reliability: 1.6% of the city. Another 189 tracts, 49.2%, are unreliable outright, and 10 more yield no rate at all. The article builds several of its sharpest claims on a measure that works in six tracts out of 384.\n\n### Why the estimates fail\n\n\n::: {.cell}\n\n```{.r .cell-code}\npov_2010 %>%\n  filter(!is.na(wht_cv), !is.infinite(wht_cv), wht_cv < 200) %>%\n  ggplot(aes(x = wht_totalE, y = wht_cv)) +\n  geom_point(alpha = 0.35, size = 1.2, color = \"#1f5c8b\") +\n  geom_hline(yintercept = 40, linetype = \"dashed\", linewidth = 0.3)+\n  annotate(\"text\", x = 5500, y = 45, label = \"Unreliable above this line\",\n           size = 2.8, color = \"grey40\", hjust = 0.5) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 12, face = \"bold\"),\n    plot.subtitle = element_text(size = 10, color = \"grey30\"),\n    axis.title = element_text(size = 9, color = \"grey30\"),\n    axis.text = element_text(size = 8),\n    panel.grid = element_blank(),\n    axis.line = element_line(linewidth = 0.2, color = \"grey70\")\n  ) +\n  labs(\n    title = \"Reliability depends on how many white residents a tract has\",\n    subtitle = \"Each dot is one Philadelphia tract, 2006-2010 ACS\",\n    x = \"White population for whom poverty status is determined\",\n    y = \"Coefficient of variation(%)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Kasat_Assignment_3_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nOf the 370 tracts with a measurable white poverty rate in both periods, 72 show a change that is statistically detectable and 298 do not.\n\n### The citywide rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncity_2017 <- pov_2017 %>%\n  st_drop_geometry() %>%\n  summarise(\n    poor_total = sum(pov_poorE, na.rm = TRUE),\n    poor_moe = moe_sum(pov_poorM, pov_poorE, na.rm = TRUE),\n    univ_total = sum(pov_totalE, na.rm = TRUE),\n    univ_moe = moe_sum(pov_totalM, pov_totalE, na.rm = TRUE)\n  ) %>%\n  mutate(\n    city_rate = poor_total / univ_total * 100,\n    city_moe = moe_prop(poor_total, univ_total, poor_moe, univ_moe) * 100\n  )\n\ncity_2017\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  poor_total poor_moe univ_total univ_moe city_rate  city_moe\n1     393924  8321.62    1526582 10140.92  25.80431 0.5174618\n```\n\n\n:::\n:::\n\n\n\n## Part 3 : Adjudicate\n\n**Supported:** The citywide poverty rate of 26% holds: aggregating all 384 tracts gives 25.8%, margin of error half a percentage point. This is the article's largest-scale claim and its most secure one, because summing 384 tracts shrinks the relative error to a fraction of what it is in any single tract. The article is also right not to compare overlapping periods.\n\n**Not supported:** The citywide white poverty figure (14.8% to 19.4%) comes from a one-year survey dropped into a story otherwise built on five-year estimates; Census guidance says not to compare the two. The framing fails too. Of 376 tracts, 36 show a detectable increase, 27 show a detectable decline the article never mentions, and 313 show no change distinguishable from zero. That is not a city sliding into poverty. It is a city where most places held steady and the rest moved both ways.\n\n**Cannot be determined:** Philadelphia neighborhoods are not Census geographies, and the reporters never published which tracts they aggregated into which neighborhood. Fairhill's 61%, Eastwick's 12% to 26%, Holmesburg's 2% to 19%, Mayfair's 1% to 14%, and the 22-neighborhood claim are therefore uncheckable. The white poverty claims fail twice over: only 6 of 384 tracts produce a reliable white poverty rate, and 189 are unreliable outright. A 1% or 2% rate in a tract with few white residents is not a precise measurement of a small number. It is an imprecise measurement that lands on one.\n\n## Part 4: Rewrite\n\nRewriting the article's opening paragraph:\n\n> A new five-year federal survey puts Philadelphia's poverty rate at about 26%, a figure the data supports with precision. What it does not support is a story of a city uniformly sliding into poverty. The Census divides Philadelphia into roughly 380 small statistical areas. Between the 2006-2010 and 2013-2017 surveys, fewer than 10% of them show a poverty increase large enough to be told apart from survey error. About 7% show a decrease. The remaining 83% moved too little, or were measured too imprecisely, to say either way. The survey is weakest where the headlines are loudest: in half the city it cannot measure white poverty reliably at all, because too few white residents live there to sample well. Philadelphia's poverty is real and citywide. Whether it is rising or falling block by block is mostly beyond what this data can show.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "Kasat_Assignment_3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}